; async tasks 全局配置
; 用法: :AsyncTask file-run

[file-run]
command = python3 "$(VIM_FILEPATH)"
output  = terminal
pos     = snacks

[file-run-lua]
command = lua "$(VIM_FILEPATH)"
output  = terminal
pos     = snacks

[file-run-sh]
command = bash "$(VIM_FILEPATH)"
output  = terminal
pos     = snacks
