set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g escape-time 0
set -g history-limit 50000
set -g display-time 3000
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g detach-on-destroy off
set -g set-clipboard on

unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g mouse on

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind Tab last-window
bind -r n next-window
bind -r p previous-window
bind -r C-h previous-window
bind -r C-l next-window
bind w choose-tree -w
bind f command-prompt "find-window '%%'"
bind . command-prompt "move-window -t %%"
bind '"' command-prompt -p index "select-window -t ':%%'"
bind & confirm-before -p "kill-window #W? (y/n)" kill-window

bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded"
bind R command-prompt "rename-window %%"
bind , command-prompt "rename-session %%"
bind s choose-tree -s
bind S run "~/.config/tmux/plugins/tmux-resurrect/scripts/save.sh"
bind D choose-client
bind x kill-pane
bind q confirm-before -p "kill-window #W? (y/n)" kill-window
bind / list-keys

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g status-interval 5
set -g status-left-length 100
set -g status-right-length 100

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

set -g @catppuccin_status_left_separator " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_connect_separator "no"

set -g status-left "#{E:@catppuccin_status_session}#{E:@catppuccin_status_application}"
set -g status-right "#{E:@catppuccin_status_date_time}#{E:@catppuccin_status_host}"

set -g @catppuccin_date_time_text " %Y-%m-%d %H:%M"

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "tmux-plugins/tmux-yank"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"
set -g @plugin "catppuccin/tmux"

set -g @continuum-restore "on"
set -g @resurrect-capture-pane-contents "on"
set -g @resurrect-strategy-vim "session"

run "~/.config/tmux/plugins/tpm/tpm"
