# ── dms managed ──
source=~/.config/mango/dms/colors.conf
source=~/.config/mango/dms/layout.conf
source=~/.config/mango/dms/outputs.conf

# ── mango modules ──
source=./effect.conf
source=./animation.conf
source=./tiling.conf
source=./appearance.conf
source=./overview.conf
source=./misc.conf

# ── sub configs ──
source=./env.conf
source=./bind.conf
source=./rule.conf
source=./monitor.conf
source=./tag.conf

# ── autostart ──
exec-once=~/.config/mango/autostart.sh

