# ── 显示器规则 ──
# 格式: monitorrule=name:<名称>,width:<宽>,height:<高>,refresh:<刷新率>,x:<x>,y:<y>,scale:<缩放>,vrr:<可变刷新率>,rr:<旋转>
# monitorrule=name:eDP-1,width:1920,height:1080,refresh:60,x:0,y:10,scale:1,vrr:0,rr:0
monitorrule=name:HDMI-A-1,width:1920,height:1080,refresh:60,x:0,y:0,scale:1,vrr:0,rr:0
monitorrule=name:HDMI-A-2,width:1920,height:1080,refresh:60,x:0,y:1080,scale:1,vrr:0,rr:0
